networks:
  public:
    external: true
services:
  app:
    command: sh -c "npm ci && npm run build && node .next/standalone/server.js"
    container_name: chis-blog
    environment:
      - HOSTNAME=0.0.0.0
    image: node:24-alpine
    labels:
      - traefik.enable=true
      - traefik.http.routers.blog.rule=Host(`chis.dev`)
      - traefik.http.routers.blog.entrypoints=websecure
      - traefik.http.routers.blog.tls.certresolver=cloudflare
      - traefik.http.services.blog.loadbalancer.server.port=3000
      - traefik.docker.network=public
    networks:
      - public
    restart: always
    volumes:
      - .:/app
    working_dir: /app
