version: '3.8'

services:
  blog:
    image: denoland/deno:alpine-1.40.2
    container_name: deno_blog
    ports:
      - "8034:8000"
    volumes:
      - .:/app
      - ./posts:/app/posts
      - ./public:/app/public
      - ./views:/app/views
    working_dir: /app
    command: deno run --allow-read --allow-net --allow-env --watch main.ts
    healthcheck:
      test: ["CMD", "deno", "eval", "console.log('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
