version: '3.8'

services:
  blog:
    image: denoland/deno:alpine-1.37
    container_name: deno_blog
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./posts:/app/posts
      - ./public:/app/public
      - ./views:/app/views
    working_dir: /app
    command: deno run --allow-read --allow-net --watch main.ts
