version: '3.6'
services:
  dev:
    image: chrisae9/website:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/website/src # Links the source files to the running container
    ports:
      - '6114:8000'
  prod:
    image: chrisae9/website:prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'unless-stopped'
    ports:
      - '6115:80'
