version: '3.8'

services:
  blog:
    build: .
    container_name: deno_blog
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./posts:/app/posts
      - ./public:/app/public 
      - ./views:/app/views
    environment:
      - DENO_INSTALL=/deno
      - PATH=/deno/bin:${PATH}
    command: deno run --allow-read --allow-net --watch main.ts
