services:
  app:
    image: node:18-alpine
    user: "1000:1000"
    environment:
      - NODE_ENV=development
    ports:
      - "5174:5173"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "rm -rf node-modules/ && npm install && npm run dev"
