services:
  app:
    image: node:18-alpine
    network_mode: host
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "rm -rf node-modules/ && npm install && npm run dev"